### ISSUE TITLE
Game: Presenter-led trivia

### ISSUE THREAD

**Issue by staff0rd** [staff0rd/DigitalIcebreakers#25]
Inspirations from pub-style trivia. Can be based on the existing _Poll_ game.

Unlike actual pub-style where questions are asked as a round, and then answers are revealed at the end of the round, this implementation would instead follow the pattern of Question/Answer > Reveal > Question/Answer > Reveal etc.

Must-haves

- [x] Presenter - Score/leaderboard
- [x] Presenter - Editing questions - Indicate correct answer
- [x] Presenter - Displaying questions - Correct answer reveal 
- [x] Client - Cache locked in answers
- [x] On presenter refresh, query server cache for existing responses
- [x] On `gotoNextQuestion`, force `QuestionAndResponse` so answer is not revealed
- [x] Block users from responding to a question while the answer is displayed
- [x] x/y label on question view

Nice-to-haves
- [ ] Presenter - Questions with images
- [ ] Client - Free-text entry
- [x] Open Trivia DB integration
- [x] Hide the scoreboard button if no questions have correct answers configured
- [ ] Time based questions
- [x] Randomised answer position

Implementation details
* No validation exists on whether the presenter has set a correct answer on each question. If no correct answer is set for a question, then that question does not affect the scoreboard upon answering.

**Comment by stafford-woodside** [comment]
* Can see answers for a brief moment before switching
* Mobiles didn't update at one stage
    * First transition only
* Lenka thinks one of her answers didn't go thru
* Should just select the answer
* Could have final screen on mobile
* Put the question on the mobile device
* Don't show answers unless presenter was displaying them

**Comment by staff0rd** [comment]
* Can see answers for a brief moment before switching
* Mobiles didn't update at one stage
    * First transition only
* Lenka thinks one of her answers didn't go thru
* Should just select the answer
* Could have final screen on mobile
* Put the question on the mobile device
* Don't show answers unless presenter was displaying them

**Comment by staff0rd** [comment]
> Put the question on the mobile device

You were right @nellysattari :) Now the question appears along with the answers on the player's mobiles. Added in 7e22d2562aab09c4eababc85cc42478509b858d6

**Comment by kcootedinh** [comment]
Feel free to deny these or drop them into separate issues:

- [ ] Time based questions
- [ ] Randomised answer position

**Comment by staff0rd** [comment]
Nice, I added them to the top. Randomised answer position would be super simple, need more info on the expectations of Time based questions?

**Comment by kcootedinh** [comment]
I think the overall idea of time-based questions would be to assist the presenter and participants with communicating how long there is to answer questions. Rather than the presenter waiting until a certain amount of responses have come in.

**Comment by kcootedinh** [comment]
I guess this would mean locking the client out from answering after the time limit has expired. The time limit would probably apply to the whole game, than be per question.

**Comment by kcootedinh** [comment]
I intend to help add these if I can. Another idea, being about to group questions into rounds, where instead of moving to the next question the scoreboard, or a round/category title shows, or both.

**Comment by staff0rd** [comment]
Most of this is implemented. Will close this for now until further testing/usage validates what's currently there.
